server:
  port: 8080
spring:
  application:
    name: badminton
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db?currentSchema=quest_badminton
    hikari:
      schema: quest_badminton
      maximum-pool-size: 10
      connection-timeout: 60000
      leak-detection-threshold: 30000
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  liquibase:
    enabled: true
    change-log: db/master.xml
    default-schema: quest_badminton
  mail:
    host: smtp.gmail.com
    port: 587
    username: questbmt@gmail.com
    password: ${GMAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
application:
  jwt:
    secret: ${JWT_SECRET:}
  redirect:
    register-confirm: http://localhost:8080/register/confirm?token=
